### ISSUE TITLE
Fix the beginning tests

### ISSUE THREAD

**Issue by marizqlav** [marolmmar1/decide-part-camaron-3#46]
**Description**: When a test was carried out to see if the tests were still running after having uploaded the changes, it was observed in the console that several tests gave errors such as: test_create_voting_from_api and test_to_string.
	
**Environment used**: I am using an Intel i7 in Window and working in a virtual machine.

**Steps to follow to get the error**:
	-Run the test (./manage.py test)

**Suggestion**: For the test_to_string, create_voting was modified by modifying the opt; opt = QuestionOption(question=q, option='option {}'.format(i+1), number=i+2)
For the test_create_voting_from_api it was added in the data: 'voting_type': 'S', .

**Comment by IsmaelHerrera2000** [comment]
The solution has been integrated and is now corrected.
